### ISSUE TITLE
ITMS-91056: Invalid privacy manifest

### ISSUE THREAD

**Issue by techouse** [Zentrust/OTPublishersHeadlessSDK#32]
I just received an email from App Store Connect citing that my app that integrates the OneTrust iOS SDK lacks a privacy manifest

> ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/OTPublishersHeadlessSDK.framework/PrivacyInfo.xcprivacy”. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app’s privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by salvatoreboemia** [comment]
Me too. 

I think in the privacy manifest you missed other mandatory keys or some keys is not filled properly

![image](https://github.com/Zentrust/OTPublishersHeadlessSDK/assets/20614870/ed3d1960-78d2-415a-8c4f-7eb3c5484f09)

Please fix it 

Thanks

**Comment by techouse** [comment]
> I think in the privacy manifest they missed other mandatory keys or some keys is not filled properly

I think it's more likely that Apple suddenly changed their requirements, because the [PrivacyInfo.xcprivacy](https://github.com/Zentrust/OTPublishersHeadlessSDK/blob/main/Sources/OTPublishersHeadlessSDK.xcframework/ios-arm64/OTPublishersHeadlessSDK.framework/PrivacyInfo.xcprivacy) hasn't been changed in ~2mos.

**Comment by davidzampier** [comment]
It's a new requirement from Apple: https://developer.apple.com/news/?id=3d8a9yyh. This has to be updated by the end of April otherwise it won't be possible to upload new builds to App Store Connect.

**Comment by techouse** [comment]
I have created a support ticket with OneTrust and got this response

> We are currently reviewing the Privacy manifest internally, changes to the Privacy Manifest will be shared in the release notes which you can subscribe to:
> 
> https://my.onetrust.com/s/release-notes

I have asked them to update this Github issue once it's resolved.

**Comment by harshbytes9026** [comment]
I think there is one Privacy Policy manifest available. Please check the exact file here: 
https://github.com/Zentrust/OTPublishersHeadlessSDK/blob/7bdaaa05c6080d288fe811a809dd137a58f431d4/Sources/OTPublishersHeadlessSDK.xcframework/ios-arm64/OTPublishersHeadlessSDK.framework/PrivacyInfo.xcprivacy

**Comment by bwake2021** [comment]
We thought this was fixed. Then. we got another email from App Store Connect that the privacy manifest was invalid. We found two empty dictionaries in the privacy manifest for `202403.1.3`. We're updating to `202404.1.0`, which does not have the empty dictionaries. This is not only annoying but expensive.

**Comment by techouse** [comment]
Same here. What's most annoying is the lack of communication. 😑

**Comment by joaosouza-traxretail** [comment]
@bwake2021 Hi! Updating to 202404.1.0 fixed your problem when uploading a binary to the App Store? We did and we still see the same error.

**Comment by bwake2021** [comment]
It did _not_. We just uploaded a build. App Store Connect reports "Invalid Binary".

**Comment by bwake2021** [comment]
Our problem was a botched merge I made. We'll see if we fixed it, in a bit.
